services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: peetopee
      POSTGRES_PASSWORD: peetopee
      POSTGRES_DB: peetopee
    ports:
      - "5433:5432"
    volumes:
      - devpg:/var/lib/postgresql/data
volumes:
  devpg:
